export const cardData = [
  {id: 1, letter: 'A', flipped: false, matched: false},
  {id: 2, letter: 'B', flipped: false, matched: false},
  {id: 3, letter: 'C', flipped: false, matched: false},
  {id: 4, letter: 'D', flipped: false, matched: false},
  {id: 5, letter: 'E', flipped: false, matched: false},
  {id: 6, letter: 'F', flipped: false, matched: false},
  {id: 7, letter: 'G', flipped: false, matched: false},
  {id: 8, letter: 'H', flipped: false, matched: false},
  {id: 9, letter: 'A', flipped: false, matched: false},
  {id: 10, letter: 'B', flipped: false, matched: false},
  {id: 11, letter: 'C', flipped: false, matched: false},
  {id: 12, letter: 'D', flipped: false, matched: false},
  {id: 13, letter: 'E', flipped: false, matched: false},
  {id: 14, letter: 'F', flipped: false, matched: false},
  {id: 15, letter: 'G', flipped: false, matched: false},
  {id: 16, letter: 'H', flipped: false, matched: false},
];
